// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ChangePasswordValidoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void changePasswordValido() {
    driver.get("https://hmissesion920200514114002.azurewebsites.net/");
    vars.put("emailrandom", js.executeScript("return \"ual-\" + Math.floor(Math.random()*1500000)+\"@ual.es\""));
    vars.put("pass", js.executeScript("return \"Password1234$\""));
    System.out.println(vars.get("emailrandom").toString());
    System.out.println(vars.get("pass").toString());
    driver.manage().window().setSize(new Dimension(1294, 1400));
    driver.findElement(By.linkText("Register")).click();
    driver.findElement(By.id("Input_Email")).click();
    driver.findElement(By.id("Input_Email")).sendKeys(vars.get("emailrandom").toString());
    driver.findElement(By.id("Input_Password")).sendKeys(vars.get("pass").toString());
    driver.findElement(By.id("Input_ConfirmPassword")).sendKeys(vars.get("pass").toString());
    driver.findElement(By.cssSelector(".pb-3")).click();
    driver.findElement(By.id("registerSubmit")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Register confirmation"));
    driver.findElement(By.id("confirm-link")).click();
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("Input_Email")).click();
    driver.findElement(By.id("Input_Email")).sendKeys(vars.get("emailrandom").toString());
    driver.findElement(By.id("Input_Password")).sendKeys(vars.get("pass").toString());
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.linkText("Hello vars.get("emailrandom").toString()!")).click();
    driver.findElement(By.xpath("//a[contains(.,\'Password\')]")).click();
    driver.findElement(By.id("Input_OldPassword")).click();
    driver.findElement(By.id("Input_OldPassword")).click();
    driver.findElement(By.id("Input_OldPassword")).sendKeys(vars.get("pass").toString());
    driver.findElement(By.id("Input_NewPassword")).sendKeys("Password12$");
    driver.findElement(By.id("Input_ConfirmPassword")).sendKeys("Password12$");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.findElement(By.cssSelector(".alert")).getText(), is("×\\\\nYour password has been changed."));
    driver.findElement(By.cssSelector(".btn-link")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Log out"));
    driver.findElement(By.linkText("HMISSesion9")).click();
    driver.findElement(By.cssSelector(".display-4")).click();
    assertThat(driver.findElement(By.cssSelector(".display-4")).getText(), is("¡Buenos días!"));
    driver.findElement(By.cssSelector("html")).click();
    driver.close();
  }
}
